// ***********************************************************************
// Assembly         : HelpCleaner
// Author           : Antonio (Joe) Colino
// Created          : 02-07-2016
// Last Modified By : Antonio (Joe) Colino
// Last Modified On : 02-08-2016
// ***********************************************************************
// <copyright file="Program.cs" company="RegularJoeSoftware Corporation">
//     Copyright (c) RegularJoeSoftware Corporation. All rights reserved.
// </copyright>
// <summary>
// THIS CODE AND INFORMATION IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR A PARTICULAR PURPOSE.
// </summary>
// ***********************************************************************
namespace HelpCleaner
{
    #region Using Directives

    using System;

    #endregion

    /// <summary>
    /// Class Program.
    /// </summary>
    public static class Program
    {

        /// <summary>
        /// The HTML help directory
        /// </summary>
        /// The help directory generated by ghostdoc 
        /// ( ie: private const string HtmlHelpDirectory = "C:\\Users\\Joe\\Documents\\Visual Studio 2015\\Projects\\EnvVarCleaner\\Help\\html"; ).
        /// If you leave it empty it will try to find it itself in relation to itself.
        private const string HtmlHelpDirectory = "";

        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        private static void Main(string[] args)
        {
            HelpDirectoryWalker walker = new HelpDirectoryWalker(HtmlHelpDirectory);
            Console.WriteLine( walker.RootPath );
            walker.Walk( );
            Console.Read( );
        }
    }
}

